# Generated by Django 4.2.30 on 2026-05-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_merge_20260530_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='category',
            field=models.CharField(blank=True, choices=[('dangerous_object', 'Objeto peligroso'), ('unauthorized_object', 'Objeto no autorizado'), ('animal', 'Animal'), ('face', 'Facial'), ('ppe', 'EPP'), ('camera', 'Cámara')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='object_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='severity',
            field=models.CharField(blank=True, choices=[('critical', 'Crítico'), ('high', 'Alto'), ('medium', 'Medio'), ('low', 'Bajo'), ('info', 'Informativo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='should_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('face_recognized', 'Rostro reconocido'), ('face_unknown', 'Rostro desconocido'), ('dangerous_object', 'Objeto peligroso detectado'), ('unauthorized_object', 'Objeto no autorizado detectado'), ('animal_detected', 'Animal detectado'), ('ppe_missing', 'Falta de EPP'), ('ppe_incorrect', 'Uso incorrecto de EPP'), ('camera_error', 'Error de cámara')], max_length=50),
        ),
    ]
