# Generated by Django 6.0.5 on 2026-06-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_securityevent_review_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_label', models.CharField(help_text='Nombre exacto que devuelve el modelo. Ejemplo: knife, cell phone, backpack.', max_length=100, unique=True)),
                ('aliases', models.TextField(blank=True, help_text='Nombres alternativos separados por coma. Ejemplo: cuchillo, arma blanca.', null=True)),
                ('category', models.CharField(choices=[('dangerous', 'Objeto peligroso'), ('unauthorized', 'Objeto no autorizado'), ('animal', 'Animal'), ('ppe', 'EPP'), ('allowed', 'Permitido / bajo riesgo')], max_length=30)),
                ('risk_level', models.CharField(choices=[('CRITICO', 'Crítico'), ('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], max_length=20)),
                ('event_type', models.CharField(choices=[('authorized_object', 'Objeto autorizado'), ('dangerous_object', 'Objeto peligroso'), ('unauthorized_access', 'Acceso no autorizado')], max_length=50)),
                ('should_alert', models.BooleanField(default=True, help_text='Si está activo, el evento se considera alerta visual. Si no, solo se registra.')),
                ('is_active', models.BooleanField(default=True)),
                ('min_confidence', models.FloatField(default=0.5, help_text='Confianza mínima para aceptar la detección. Valor entre 0 y 1.')),
                ('cooldown_seconds', models.PositiveIntegerField(default=20, help_text='Tiempo mínimo entre eventos repetidos del mismo objeto.')),
                ('requires_duration', models.BooleanField(default=False, help_text='Usar cuando el objeto solo debe alertar después de permanecer cierto tiempo.')),
                ('max_allowed_seconds', models.PositiveIntegerField(default=0, help_text='Tiempo permitido antes de registrar el evento. Ejemplo: celular por más de 60 segundos.')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de detección',
                'verbose_name_plural': 'Reglas de detección',
                'ordering': ['category', 'risk_level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='securityevent',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('CRITICO', 'Crítico'), ('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], max_length=20, null=True),
        ),
    ]
