# Generated by Django 4.2.30 on 2026-06-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0013_securityevent_vision_event_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='restricted_zone_enabled',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='restricted_zone_height',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='restricted_zone_name',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='restricted_zone_width',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='restricted_zone_x',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='restricted_zone_y',
        ),
        migrations.AddField(
            model_name='camera',
            name='api_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('face_recognized', 'Rostro reconocido'), ('face_unknown', 'Rostro desconocido'), ('ppe_missing', 'Falta de EPP'), ('intrusion', 'Intrusión'), ('authorized_object', 'Objeto autorizado'), ('unauthorized_object', 'Objeto no autorizado'), ('dangerous_object', 'Objeto peligroso detectado'), ('fall_detected', 'Movimiento'), ('phone_usage', 'Distraccion'), ('collision_risk', 'Riesgo de choque'), ('cut_risk', 'Riesgo de corte'), ('unauthorized_access', 'Acceso no autorizado')], max_length=50),
        ),
    ]
