# Generated by Django 4.2.30 on 2026-06-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0014_remove_camera_restricted_zone_enabled_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "camera_securityevent" '
                        'ADD COLUMN IF NOT EXISTS "object_label" varchar(100) NULL;'
                    ),
                    reverse_sql=(
                        'ALTER TABLE "camera_securityevent" '
                        'DROP COLUMN IF EXISTS "object_label";'
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='securityevent',
                    name='object_label',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='securityevent',
            name='should_alert',
            field=models.BooleanField(default=True),
        ),
    ]
