# Generated by Django 4.2.30 on 2026-06-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0015_securityevent_object_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='push_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
