# Generated by Django 4.2.30 on 2026-06-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0016_camera_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='api_token',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
