# Generated by Codex on 2026-06-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0017_alter_camera_api_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="api_token",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="push_token",
        ),
    ]
