# Generated by Django 4.2.30 on 2026-08-16 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0010_detectionrule_securityevent_category_and_more'),
        ('camera', '0021_camera_stream_path'),
    ]

    operations = [
    ]
