# Generated by Django 4.2.30 on 2026-08-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0022_merge_20260815_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
