"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_int(name, default):
    try:
        return int(os.getenv(name, str(default)))
    except (TypeError, ValueError):
        return default


def env_float(name, default):
    try:
        return float(os.getenv(name, str(default)))
    except (TypeError, ValueError):
        return default


# Criterios operativos del sistema, definidos a partir de la tabla de
# caracteristicas validada del sistema web.
SYSTEM_LIVE_VIDEO_RESPONSE_TARGET_SECONDS = env_float(
    "SYSTEM_LIVE_VIDEO_RESPONSE_TARGET_SECONDS",
    1.2,
)
SYSTEM_LIVE_VIDEO_MAX_RESPONSE_SECONDS = env_float(
    "SYSTEM_LIVE_VIDEO_MAX_RESPONSE_SECONDS",
    3.0,
)
SYSTEM_TARGET_VIDEO_FPS = env_int("SYSTEM_TARGET_VIDEO_FPS", 8)
SYSTEM_MAX_INTERNAL_VIDEO_FPS = env_int("SYSTEM_MAX_INTERNAL_VIDEO_FPS", 12)
SYSTEM_ALERT_EMAIL_TARGET_SECONDS = env_int("SYSTEM_ALERT_EMAIL_TARGET_SECONDS", 8)
SYSTEM_ALERT_EMAIL_MAX_SECONDS = env_int("SYSTEM_ALERT_EMAIL_MAX_SECONDS", 9)
SYSTEM_EXPECTED_UPTIME_PERCENT = env_float("SYSTEM_EXPECTED_UPTIME_PERCENT", 95.0)
SYSTEM_EVENTS_REFRESH_MS = env_int("SYSTEM_EVENTS_REFRESH_MS", 5000)
SYSTEM_LIVE_LOG_REFRESH_MS = env_int("SYSTEM_LIVE_LOG_REFRESH_MS", 800)
SYSTEM_CAMERA_STATUS_REFRESH_MS = env_int("SYSTEM_CAMERA_STATUS_REFRESH_MS", 3000)
SYSTEM_MODEL_PRECISION_EXPECTED = env_float("SYSTEM_MODEL_PRECISION_EXPECTED", 85.0)
SYSTEM_MODEL_PRECISION_OBTAINED = env_float("SYSTEM_MODEL_PRECISION_OBTAINED", 87.25)
SYSTEM_MODEL_RECALL_EXPECTED = env_float("SYSTEM_MODEL_RECALL_EXPECTED", 90.0)
SYSTEM_MODEL_RECALL_OBTAINED = env_float("SYSTEM_MODEL_RECALL_OBTAINED", 93.21)
SYSTEM_MODEL_MAP50_EXPECTED = env_float("SYSTEM_MODEL_MAP50_EXPECTED", 90.0)
SYSTEM_MODEL_MAP50_OBTAINED = env_float("SYSTEM_MODEL_MAP50_OBTAINED", 96.04)
SYSTEM_OPERATION_CRITERIA = {
    "desempeno": {
        "live_video_response_seconds": {
            "expected": f"< {SYSTEM_LIVE_VIDEO_MAX_RESPONSE_SECONDS:g}",
            "obtained": SYSTEM_LIVE_VIDEO_RESPONSE_TARGET_SECONDS,
        },
        "detection_fps": {
            "expected": f">= {SYSTEM_TARGET_VIDEO_FPS}",
            "obtained": SYSTEM_TARGET_VIDEO_FPS,
            "internal_max": SYSTEM_MAX_INTERNAL_VIDEO_FPS,
        },
        "email_alert_seconds": {
            "expected": "< 10",
            "obtained": SYSTEM_ALERT_EMAIL_TARGET_SECONDS,
        },
        "uptime_percent": {
            "expected": f">= {SYSTEM_EXPECTED_UPTIME_PERCENT:g}",
            "obtained": SYSTEM_EXPECTED_UPTIME_PERCENT,
        },
    },
    "deteccion_yolov8": {
        "ppe_precision_percent": {
            "expected": SYSTEM_MODEL_PRECISION_EXPECTED,
            "obtained": SYSTEM_MODEL_PRECISION_OBTAINED,
        },
        "ppe_recall_percent": {
            "expected": SYSTEM_MODEL_RECALL_EXPECTED,
            "obtained": SYSTEM_MODEL_RECALL_OBTAINED,
        },
        "map50_percent": {
            "expected": SYSTEM_MODEL_MAP50_EXPECTED,
            "obtained": SYSTEM_MODEL_MAP50_OBTAINED,
        },
        "restricted_zone_intrusion": {
            "expected": "deteccion correcta",
            "obtained": "deteccion facial y registro de personas implementado",
            "compliance": "parcial",
        },
    },
    "usabilidad": {
        "interface_clarity_percent": {"expected": 85.0, "obtained": 90.0},
        "events_panel_refresh_ms": {"expected": 5000, "obtained": SYSTEM_EVENTS_REFRESH_MS},
    },
}

#Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [
       host.strip()
       for host in os.getenv("ALLOWED_HOSTS","").split(",")
       if host.strip()
        ]

CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in os.getenv("CSRF_TRUSTED_ORIGINS","").split(",")
        if origin.strip()
        ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core_apps.camera',
    'core_apps.common',
    'channels',
    'core_apps.informes'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core_apps.common.context_processors.user_role',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = os.getenv("STATIC_URL", "/static/")
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Configuración de seguridad para desarrollo
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "False").lower() == "true"
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "False").lower() == "true"
SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "False").lower() == "true"

MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER or "no-reply@smri.local",
)
EMAIL_TIMEOUT = min(
    env_int("EMAIL_TIMEOUT", SYSTEM_ALERT_EMAIL_TARGET_SECONDS),
    SYSTEM_ALERT_EMAIL_MAX_SECONDS,
)

# YOLOv8 / Ultralytics - objetos de riesgo.
RISK_YOLO_MODEL_PATH = BASE_DIR / "camera" / "weights" / "yolov8s.pt"
RISK_YOLO_CONF = 0.25
RISK_YOLO_IMGSZ = 960
RISK_YOLO_FRAME_INTERVAL = env_int("RISK_YOLO_FRAME_INTERVAL", 30)
RISK_YOLO_CLASSES = [14, 15, 16, 24, 26, 28, 39]
RISK_YOLO_ALERT_CONF = {
    "cat": 0.25,
    "dog": 0.25,
    "bird": 0.25,
    "backpack": 0.35,
    "handbag": 0.35,
    "suitcase": 0.35,
    "bottle": 0.35,
}

FACE_RECOGNITION_FRAME_INTERVAL = env_int("FACE_RECOGNITION_FRAME_INTERVAL", 16)
FACE_DETECTION_FRAME_INTERVAL = env_int("FACE_DETECTION_FRAME_INTERVAL", 12)
FACE_ANALYSIS_WIDTH = env_int("FACE_ANALYSIS_WIDTH", 480)
FACE_RECOGNITION_TOLERANCE = env_float("FACE_RECOGNITION_TOLERANCE", 0.65)
FACE_UNAUTHORIZED_CONFIRMATION_FRAMES = env_int("FACE_UNAUTHORIZED_CONFIRMATION_FRAMES", 3)
FACE_UNAUTHORIZED_DISPLAY_FRAMES = env_int("FACE_UNAUTHORIZED_DISPLAY_FRAMES", 2)
FACE_AUTH_MEMORY_SECONDS = env_float("FACE_AUTH_MEMORY_SECONDS", 10.0)
FACE_MIN_BOX_WIDTH_RATIO = env_float("FACE_MIN_BOX_WIDTH_RATIO", 0.020)
FACE_MIN_BOX_HEIGHT_RATIO = env_float("FACE_MIN_BOX_HEIGHT_RATIO", 0.030)
PPE_FRAME_INTERVAL = env_int("PPE_FRAME_INTERVAL", 45)
PPE_INFERENCE_IMGSZ = env_int("PPE_INFERENCE_IMGSZ", 960)
PPE_MODEL_CONFIDENCE = env_float("PPE_MODEL_CONFIDENCE", 0.20)
PPE_PERSON_CONFIDENCE = env_float("PPE_PERSON_CONFIDENCE", 0.40)
PPE_MASK_CONFIDENCE = env_float("PPE_MASK_CONFIDENCE", 0.30)
PPE_NO_MASK_CONFIDENCE = env_float("PPE_NO_MASK_CONFIDENCE", 0.50)

# Camara RTSP por defecto para pruebas directas fuera del modelo Camera.
RTSP_CAMERA_URL = os.getenv(
    "RTSP_CAMERA_URL",
    "rtsp://admin:TU_PASSWORD@192.168.10.198:554/stream1",
)
RTSP_CAMERA_URL_FAST = os.getenv(
    "RTSP_CAMERA_URL_FAST",
    "rtsp://admin:TU_PASSWORD@192.168.10.198:554/stream2",
)

# Detector visual general: objetos cortopunzantes, caidas y uso de celular.
YOLO_OBJECT_MODEL_PATH = BASE_DIR / "camera" / "weights" / "yolov8s.pt"
YOLO_POSE_MODEL_PATH = BASE_DIR / "camera" / "weights" / "yolov8s-pose.pt"
YOLO_FAST_MODEL_PATH = BASE_DIR / "camera" / "weights" / "yolov8s.pt"

SHARP_OBJECT_CONF = 0.18
SHARP_OBJECT_IMGSZ = 1280
SHARP_OBJECT_CLASSES = [43, 76]
SHARP_OBJECT_ALERT_CONF = {
    "knife": 0.20,
    "scissors": 0.25,
}
SHARP_OBJECT_CONFIRMATION_FRAMES = 1
SHARP_OBJECT_TTL_SECONDS = 2.0

POSE_CONF = 0.35
POSE_IMGSZ = 640
POSE_KEYPOINT_CONF = 0.25
FALL_SECONDS = 3.0
FALL_ASPECT_RATIO = 1.70
FALL_TORSO_ANGLE = 68
FALL_MIN_BOX_AREA_RATIO = 0.08
FALL_MIN_WIDTH_RATIO = 0.28
FALL_TRACK_TTL_SECONDS = 4.0

PHONE_CONF = 0.30
PHONE_IMGSZ = 960
PHONE_ALERT_SECONDS = 10
PHONE_UNIDENTIFIED_ALERT_SECONDS = 0
PHONE_UNAUTHORIZED_ALERT_SECONDS = 0
PHONE_AREA_ALERT_SECONDS = 0
PHONE_AREA_CONF = 0.65
PHONE_AREA_CONFIRMATION_FRAMES = 2
PHONE_TRACK_TTL_SECONDS = 8.0
PHONE_PERSON_BOX_EXPAND_RATIO = 0.18
PHONE_CLASSES = [0, 67]

DETECT_SHARP_EVERY_N_FRAMES = env_int("DETECT_SHARP_EVERY_N_FRAMES", 6)
DETECT_POSE_EVERY_N_FRAMES = env_int("DETECT_POSE_EVERY_N_FRAMES", 35)
DETECT_PHONE_EVERY_N_FRAMES = env_int("DETECT_PHONE_EVERY_N_FRAMES", 4)
EVENT_COOLDOWN_SECONDS = env_int("EVENT_COOLDOWN_SECONDS", 10)
RTSP_INITIAL_FRAME_TIMEOUT_SECONDS = env_int("RTSP_INITIAL_FRAME_TIMEOUT_SECONDS", 15)
RTSP_STALE_FRAME_SECONDS = env_float("RTSP_STALE_FRAME_SECONDS", 2.0)
RTSP_TRANSPORT = os.getenv("RTSP_TRANSPORT", "tcp")

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
